data:
  tidigits:
    dir_path: "data/TIDIGITS"
    pickle_path: "data/TIDIGITS/pickle"
  noise:
    dir_path: "data/freesound"
    pickle_path: "data/freesound/pickle"
    freesound_api_key: ""
split:
  ratios:
    train: 7
    test: 2
    validation: 1
  stratified: True
model_params:
  time_frames: 40 # the number of time frames each recording is split into for Fourier transform and SNN processing
  mfsc:
    freq_bands: 48 # the number of filters in the Melspace filterbank preprocessor
  dtf:
    overlap: 5 # the preferred overlap (frame len - stride) in ms for discrete Fourier transform
    pad: 5 # the length of the zero-padding in ms for each time frame in the discrete Fourier transform
  snn:
    in:
      th: 1.0 # the input layer activation threshold
    conv:
      th: 23.0 # the convolution layer activation threshold
      a_plus: 0.004 # learning rate for positive stdp
      a_minus: 0.003 # learning rate for negative stdp
      f_maps: 50 # the number of feature maps in the convolution layer
      rec_field: 6 # the number of overlapping time frames a hidden layer neuron is receptive to
      stride: 1 # the stride (group length - overlap) of the receptive fields of hidden layer neurons
      wsg: 9 # the number of weight sharing groups in the convolutional layer
      serialisation:
        load_speech_encoder: True
        folder: "models" # directory where pickled models are stored
        load_file: "" # file name of the model to load
        save_file: "model" # file name for saving the model
      weights:
        mean: 0.8
        sd: 0.05
    pool:
      rec_field: 3 # the number of time frames a pooling layer neuron is receptive to
      stride: 3 # the stride (group length - overlap) of the receptive fields of pooling layer neurons
seed: "cattodog"
modes:
  dev: 
    enabled: True
    samples: 100
processes:
  train_snn: 
    enabled: False
    diff_th: 0.000001
    epochs: 100
    batch_size: 5
  compare_snn_mfsc:
    enabled: False
    training: True
    testing: False
    validation: False
  obtain_noise_dataset:
    enabled: True
    allowed_licenses:
      - "Creative Commons 0"
    samples: 100
    allowed_formats:
      - "wav"
    download: False
    target_sr: 20000